// constants/aesthetics.ts

export const AESTHETICS = [
    'Minimalist',
    'Old Money',
    'Vintage',
    'Dark Academia',
    'Light Academia',
    'Romantic Academia',
    'Bohemian',
    'Cottagecore',
    'Fairycore',
    'Goblincore',
    'Witchy',
    'Grunge',
    'Soft Grunge',
    'Punk',
    'Gothic',
    'Nu-Goth',
    'Pastel Goth',
    'Cyberpunk',
    'Y2K',
    'E-Girl',
    'E-Boy',
    'Baddie',
    'Streetwear',
    'Athleisure',
    'Techwear',
    'Art Hoe',
    'Indie',
    'Retro Futurism',
    'Mod',
    'Barbiecore',
    'Kawaii',
    'Classic Lolita',
    'Sweet Lolita',
    'Gothic Lolita',
    'Decora',
    'Kidcore',
    'Harajuku',
    'Scene',
    'Emo',
    'Hippie',
    'Mermaidcore',
    'Dark Fantasy',
    'Pastelcore',
    'Soft Girl',
    'Camp',
    'Coastal Grandmother',
    'Balletcore',
    'Angelcore',
    'Gyaru',
    'Cowboycore',
    'Rocker Chic',
    'Mafia Chic',
    'Royalcore',
    'Regencore',
    'Steampunk',
    'Dieselpunk',
  ] as const;
  
  export type Aesthetic = typeof AESTHETICS[number];